name: ContributionHarvest

on:
  push:
    branches:
      - main

jobs:
  display-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch contributors
        id: contributors
        run: |
          OWNER=$(echo "${{ github.repository }}" | awk -F '/' '{print $1}')
          REPO=$(echo "${{ github.repository }}" | awk -F '/' '{print $2}')
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          CONTRIBUTORS_API="https://api.github.com/repos/${OWNER}/${REPO}/contributors"
          curl -sSL -H "Authorization: token ${TOKEN}" "${CONTRIBUTORS_API}" | jq -r '.[].login' | sort -u > contributors.txt
          echo "$(git config --get user.name)" >> contributors.txt

      - name: Sort contributors
        id: sorted-contributors
        run: |
          cat contributors.txt | sort > sorted_contributors.txt

      - name: Display contributors and update README
        run: |
          cat sorted_contributors.txt | awk '{print "| " $$0 " |"}' > CONTRIBUTORS.md
          sed -i -e '/<!-- CONTRIBUTORS START -->/,/<!-- CONTRIBUTORS END -->/c\<!-- CONTRIBUTORS START -->\n| Name |\n| ---- |\n$(cat CONTRIBUTORS.md)\n| ---- |\n<!-- CONTRIBUTORS END -->' README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add CONTRIBUTORS.md README.md
          git commit -m "Update contributors in README"
          git push
