name: ContriSnap

on:
  push:
    branches:
      - main

jobs:
  fetch-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch contributors
        id: contributors
        run: |
          git log --format='%aN' | sort -u > contributors.txt
          echo "::set-output name=contributors_file::contributors.txt"

  sort-contributors:
    needs: fetch-contributors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sort contributors
        id: sorted-contributors
        run: |
          cat ${{ needs.fetch-contributors.outputs.contributors_file }} | sort > sorted_contributors.txt
          echo "::set-output name=sorted_contributors_file::sorted_contributors.txt"

  display-contributors:
    needs: sort-contributors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Display contributors
        id: display
        run: |
          cat ${{ needs.sort-contributors.outputs.sorted_contributors_file }} | awk '{print "| " $$0 " |"}' > CONTRIBUTORS.md
          echo "::set-output name=contributors_file::CONTRIBUTORS.md"

      - name: Update README
        run: |
          cp CONTRIBUTORS.md contributors_temp.md
          sed -i -e '/<!-- CONTRIBUTORS START -->/,/<!-- CONTRIBUTORS END -->/d' README.md
          awk '/<!-- CONTRIBUTORS START -->/{print;system("cat contributors_temp.md");next}1' README.md > README_updated.md
          mv README_updated.md README.md
